# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a parent image
FROM node:22.12-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json into the container at /app
COPY package.json package-lock.json ./

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Start a new stage from a fresh node image
FROM node:22-alpine AS release

WORKDIR /app

# Copy only the built output and necessary files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app

# Install only production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Set the command to run the application
ENTRYPOINT ["node", "dist/index.js"]
